name: Shared CI Templates

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string

jobs:
  workflow_on_call:
    runs-on: "ubuntu-latest"
    container: python:3.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run workflow information
        run: echo "This workflow is called by ${{ inputs.workflow_name}}"