# name: CI using repo

# # on:
# #   push:
# #     branches: ["main"]

# jobs:
#   CodeLinter:
#     runs-on: ubuntu-latest
#     container: python:3.9-slim
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: linting code
#         uses: pre-commit/action@v3.0.1
#         with:
#           extra_args: --all-files